services:

  oak-testall-sql:
    container_name: oak-testall-sql
    build:
      context: ../.
      dockerfile: docker/sql.dockerfile
    image: oak-testall-sql
    networks:
      - oak
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  oak-testall-redis:
    container_name: oak-testall-redis
    image: redis:8.0.3-alpine
    networks:
      - oak
    ports:
      - "6379:6379"

  oak-testall-minio:
    container_name: oak-testall-minio
    image: minio/minio:RELEASE.2025-07-18T21-56-31Z
    networks:
      - oak
    environment:
      MINIO_ACCESS_KEY: localtest
      MINIO_SECRET_KEY: localtest
    ports:
      - "9000:9000"
    command: "minio server /data"

networks:
  oak:
    name: oak